apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
        - name: classrooms
          image: i211221/classrooms:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  type: NodePort
  selector:
    app: classrooms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002