apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: i211221/post:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005